title: Pordier at War Wiki
description: Semi-Official Wiki
theme: jekyll-theme-primer

url: "https://pordier.wintercoat.nz"
baseurl: ""

collections:
  wiki:
    output: true
    permalink: /:path/

wiki_categories:
  - name: "Maps"
    slug: "map"
  - name: "Classes"
    slug: "class"
  - name: "Factions"
    slug: "faction"
  - name: "Game Mechanics"
    slug: "mechanic"
  - name: "Strategies"
    slug: "strategy"
