title: Pordier at War Wiki
description: Semi-official Wiki focused on the Facts
theme: jekyll-theme-primer

collections:
  wiki:
    output: true
    permalink: /:path/

wiki_categories:
  - name: "Maps"
    slug: "maps"
  - name: "Classes"
    slug: "classes"
  - name: "Factions"
    slug: "factions"
  - name: "Game Mechanics"
    slug: "game-mechanics"
